### ISSUE TITLE
don't work on standard manuals

### ISSUE THREAD

**Issue by marczz** [mle86/man-to-md#1]
I gave a try to man-to-md, while I can successfully use it on the samples from test/samples/
 directory, when trying to convert any standard man page from my linux system (like man.1 or ls.1) give an error:

     could not parse first line at man-to-md/man-to-md.pl line 413, <> line 1.

What is wrong with the roff format of standard manuals?

It also fails on a simple example like [foo.1](http://www.tldp.org/HOWTO/Man-Page/q3.html) from the [Linux Man Page Howto](http://www.tldp.org/HOWTO/Man-Page/index.html).

**Comment by mle86** [comment]
You're right of course. I missed quite a few standard conventions.
Then again, it hasn't hit v1.0.0 yet. :wink:
I just finished v0.8, it does a lot better with many standard man pages.
Still a long way to go.

**Comment by gudrutis** [comment]
I got the same issue:

```
could not parse first line at ./man-to-md.pl line 489, <> line 1.
```

My `.roff` file started like this:

```
.TH SCRAM 1 LOCAL
```

For some reason, if I include the following line from example `test/samples/code.roff` at the beginning of file, it works, though with some malformations. 

```
.TH "A<B>" "7" "July 2017" "a<b> 0.9.2" ""

```

Probably script expects .roff file to start with specific format.

**Comment by mle86** [comment]
Correct, the scripts expected the .TH line to contain a fourth token with the program name and version.

Check out v0.10.0, it accepts shorter .TH lines as well (and it omits the `Version ...` line in the output in this case).
