### ISSUE TITLE
could not parse first line at . . .

### ISSUE THREAD

**Issue by haakonstorm** [mle86/man-to-md#10]
```
λ man2md ls
/usr/share/man/man1/ls.1
could not parse first line at /Users/storm/bin/man2md.pl line 626, <> line 38.

λ man2md which
/usr/share/man/man1/which.1
could not parse first line at /Users/storm/bin/man2md.pl line 626, <> line 32.

λ man2md systemsetup
/usr/share/man/man8/systemsetup.8
could not parse first line at /Users/storm/bin/man2md.pl line 626, <> line 18.

λ uname -a
Darwin 10core.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

I was so happy when I found this project.
Using it to pass its output to `Cobertos/md2notion` project, to archive `man`-pages and then edit them, then to recall I use the `wrjlewis/notion-search-alfred-workflow` project to search `Notion` for the edited `man`-page. But, most of the manual pages I wanted to archive, throws an error as the above. Is this related to #5 perhaps? Since it errors out on most everything I wanted to convert perhaps this is something different? I do not know perl that well, nor the `*roff` formats, how would we proceed to get this fixed?

**Comment by mle86** [comment]
Most likely it's the same issue, yeah.
I don't have DarwinOS here but Apple's online man page resources (e.g. https://opensource.apple.com/source/file_cmds/file_cmds-272.220.1/ls/ls.1.auto.html)
suggest to me that their man pages are in _mdoc_ format, which my script doesn't support at the moment. Sorry about that!
