### ISSUE TITLE
"<" becomes "&lt;"

### ISSUE THREAD

**Issue by gudrutis** [mle86/man-to-md#2]
when coverting from `.roff` to `.md`, "<" becomes "\&lt;"

**Comment by mle86** [comment]
That's intentional because most Markdown viewers I've encountered (including Github itself) render some HTML, so they might misinterpret characters such as `<`.

Have you found a case where this results in "`&lt;`" being visible?

**Comment by gudrutis** [comment]
Mm, good point, I was just checking the text output, not how it was rendered so I forgot about this case.

Maybe you should convert '>' to '\&gt;", so it would match and would be easier to read?

**Comment by mle86** [comment]
Not necessary for the viewer,
but might be a good idea for consistency.
