### ISSUE TITLE
could not parse first line when date is on top

### ISSUE THREAD

**Issue by mpwsh** [mle86/man-to-md#5]
Hi! 
I'm receiving the following error when trying to convert nvim man page to markdown.

```
perl man-to-md.pl < $(man --where --all nvim) > nvim.md
could not parse first line at man-to-md.pl line 575, <> line 1.
```

These are thef first lines of Nvim man page.
```
.Dd December 17, 2017
.Dt NVIM 1
.Os
.Sh NAME
.Nm nvim
.Nd edit text
.Sh SYNOPSIS
.Nm
.Op Ar options
.Op Ar file ...
```

**Comment by mle86** [comment]
These are not the standard groff macros,
they're part of the _mdoc_ macro package.

I'm currently not planning on supporting them
as they seem to be rarely used
(on my machine they're in 53 out of 6675 man pages),
but maybe you'd like to submit a PR?
