### ISSUE TITLE
.TH arguments are optional

### ISSUE THREAD

**Issue by vapier** [mle86/man-to-md#6]
the script requires `.TH` provide 4 arguments, but only 2 are required.  the spec for `.TH`:
> https://www.gnu.org/software/groff/manual/html_node/Man-usage.html
> `Macro: .TH title section [extra1 [extra2 [extra3]]]`

otherwise the script fails with `could not parse first line`

**Comment by mle86** [comment]
Thanks!

**Comment by vapier** [comment]
thx, it's working for me now
